services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: assign-mate-api
    volumes:
      - .:/home/node/app
      - /home/node/app/.docker/postgres-data
    ports:
      - '3005:3000'
    networks:
      - api-network
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: assign-mate-postgres
    image: postgres:16.5
    restart: no
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-assignmate}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - '5434:5432'
    networks:
      - api-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  api-network:
    driver: bridge

volumes:
  postgres-data: