import { ApiProperty } from "@nestjs/swagger";
import { Role } from "@prisma/client";

export class User {
    @ApiProperty({
        description: "User ID, generated by UUID",
        nullable: false,
        required: true,
        type: "string",
        example: "2313w49-0db7-4v79-aacc-52624343bf2t",
    })
    id: string;

    @ApiProperty({
        description: "User's full name",
        nullable: false,
        required: true,
        type: "string",
        example: "John Sample",
    })
    name: string;

    @ApiProperty({
        description: "User's date of birth",
        nullable: false,
        required: true,
        type: "string",
        format: "date-time",
        example: "1990-01-01T00:00:00.000Z",
    })
    dateOfBirth: Date;

    @ApiProperty({
        description: "User's email address",
        uniqueItems: true,
        nullable: false,
        required: true,
        type: "string",
        example: "youremail@example.com",
    })
    email: string;

    @ApiProperty({
        description: "Timestamp when the user's email was verified",
        nullable: true,
        required: false,
        type: "string",
        format: "date-time",
        example: "2022-01-01T00:00:00.000Z",
    })
    emailVerified?: Date;

    @ApiProperty({
        description: "User's role (admin, user, professor, student)",
        nullable: false,
        required: true,
        type: "string",
        example: "user",
    })
    role: Role;

    @ApiProperty({
        description: "URL to the user's profile image",
        nullable: true,
        required: false,
        type: "string",
        example: "https://picsum.photos/200",
    })
    image?: string;

    @ApiProperty({
        description: "Timestamp when the user was created",
        nullable: false,
        required: true,
        type: "string",
        format: "date-time",
        example: "2022-01-01T00:00:00.000Z",
    })
    createdAt: Date;

    @ApiProperty({
        description: "Timestamp when the user was last updated",
        nullable: false,
        required: true,
        type: "string",
        format: "date-time",
        example: "2022-01-01T00:00:00.000Z",
    })
    updatedAt: Date;

    @ApiProperty({
        description: "Timestamp when the user was created (alias for createdAt)",
        nullable: false,
        required: true,
        type: "string",
        format: "date-time",
        example: "2022-01-01T00:00:00.000Z",
    })
    creationDate: Date;
}