import { ApiProperty } from "@nestjs/swagger";
import { Type } from "class-transformer";

export class User {
    @ApiProperty({
        description: "User ID, generated by UUID",
        example: "2313w49-0db7-4v79-aacc-52624343bf2t",
    })
    id: string;

    @ApiProperty({
        description: "User's full name",
        example: "John Sample",
    })
    name: string;

    @ApiProperty({
        description: "User's date of birth",
        format: "date-time",
        example: "1990-01-01T00:00:00.000Z",
    })
    @Type(() => Date) 
    dateOfBirth: Date;

    @ApiProperty({
        description: "User's email address",
        example: "youremail@example.com",
    })
    email: string;

    @ApiProperty({
        description: "Timestamp when the user's email was verified",
        format: "date-time",
        example: "2022-01-01T00:00:00.000Z",
        required: false,
    })
    @Type(() => Date)
    emailVerified?: Date;

    @ApiProperty({
        description: "URL to the user's profile image",
        example: "https://picsum.photos/200",
        required: false,
    })
    image?: string;

    @ApiProperty({
        description: "Timestamp when the user was created",
        format: "date-time",
        example: "2022-01-01T00:00:00.000Z",
    })
    @Type(() => Date)
    createdAt: Date;

    @ApiProperty({
        description: "Timestamp when the user was last updated",
        format: "date-time",
        example: "2022-01-01T00:00:00.000Z",
    })
    @Type(() => Date)
    updatedAt: Date;

    @ApiProperty({
        description: "Whether the user has administrative privileges",
        example: false,
        required: false,
    })
    isAdmin?: boolean;  // Campo adicionado para controlar privilégios de administrador

}
